# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WaldorfConnect
tagline:          'Die Plattform für SV-Arbeit'
description:      'Die Cloud-Plattform für Schüler-Vertretungen\n\nBring deine SV-Arbeit auf ein ganz anderes Level mit Cloud-Speicher, Team Chats, Meetings und mehr!'
url:              https://waldorfconnect.github.io
baseurl:          /documentation

author:
  name:           'Leander Christmann'
  url:            https://stackoverflow.com/users/20594090/lchristm

# Custom vars
version:          'in Beta'

github:
  repo:           https://github.com/WaldorfConnect/documentation
