# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WaldorfConnect
tagline:          'Die Plattform f체r SV-Arbeit'
description:      'Die Cloud-Plattform f체r Sch체ler-Vertretungen<br><br>Bring deine SV-Arbeit auf das n채chste Level mit Cloud-Speicher, Team Chats, Meetings und mehr!'
url:              https://waldorfconnect.github.io
baseurl:          /documentation

author:
  name:           'Leander Christmann'
  url:            https://stackoverflow.com/users/20594090/lchristm

# Custom vars
github:
  repo:           https://github.com/WaldorfConnect/documentation
